FROM node:22-alpine
WORKDIR /app
RUN corepack enable
COPY . .
RUN pnpm install --no-frozen-lockfile && pnpm --filter @temmuz/database prisma:generate && pnpm --filter @temmuz/api build
CMD ["sh", "-c", "pnpm db:migrate && pnpm --filter @temmuz/api start"]
