FROM node:22-alpine AS deps
WORKDIR /app
RUN corepack enable
COPY package.json pnpm-workspace.yaml pnpm-lock.yaml ./
COPY apps/api/package.json apps/api/package.json
COPY packages packages
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm --filter @temmuz/api build
CMD ["pnpm","--filter","@temmuz/api","start"]
