CREATE TYPE "Role" AS ENUM ('ADMIN','AGENT'); CREATE TYPE "UserStatus" AS ENUM ('ACTIVE','DISABLED'); CREATE TYPE "ConversationStatus" AS ENUM ('OPEN','WAITING','CLOSED'); CREATE TYPE "SenderType" AS ENUM ('CUSTOMER','AGENT','SYSTEM'); CREATE TYPE "VisitorEventType" AS ENUM ('PAGE_VIEW','PRODUCT_VIEW','CHAT_OPEN','CHAT_STARTED','MESSAGE_SENT','CHAT_CLOSED');
CREATE TABLE "Site" ("id" TEXT PRIMARY KEY,"siteId" TEXT UNIQUE NOT NULL,"name" TEXT NOT NULL,"domain" TEXT,"whatsappNumber" TEXT,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "AdminUser" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL,"email" TEXT UNIQUE NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'AGENT',"status" "UserStatus" NOT NULL DEFAULT 'ACTIVE',"lastSeenAt" TIMESTAMP,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Visitor" ("id" TEXT PRIMARY KEY,"siteId" TEXT NOT NULL REFERENCES "Site"("siteId"),"visitorId" TEXT NOT NULL,"sessionId" TEXT NOT NULL,"firstSeenAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastSeenAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"currentUrl" TEXT,"currentTitle" TEXT,"referrer" TEXT,"userAgent" TEXT,"deviceType" TEXT,"browser" TEXT,"operatingSystem" TEXT,"pageType" TEXT,"productId" TEXT,"productName" TEXT,"productUrl" TEXT,"category" TEXT,"online" BOOLEAN NOT NULL DEFAULT false, UNIQUE("siteId","visitorId"));
CREATE TABLE "Conversation" ("id" TEXT PRIMARY KEY,"visitorId" TEXT NOT NULL REFERENCES "Visitor"("id") ON DELETE CASCADE,"status" "ConversationStatus" NOT NULL DEFAULT 'WAITING',"assignedAgentId" TEXT REFERENCES "AdminUser"("id"),"startedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP NOT NULL,"closedAt" TIMESTAMP);
CREATE TABLE "Message" ("id" TEXT PRIMARY KEY,"conversationId" TEXT NOT NULL REFERENCES "Conversation"("id") ON DELETE CASCADE,"senderType" "SenderType" NOT NULL,"senderId" TEXT NOT NULL,"message" TEXT NOT NULL,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"deliveredAt" TIMESTAMP,"readAt" TIMESTAMP,"metadata" JSONB,"clientMessageId" TEXT,"agentId" TEXT REFERENCES "AdminUser"("id"), UNIQUE("conversationId","clientMessageId"));
CREATE TABLE "QuickReply" ("id" TEXT PRIMARY KEY,"siteId" TEXT NOT NULL REFERENCES "Site"("siteId"),"title" TEXT NOT NULL,"message" TEXT NOT NULL,"isActive" BOOLEAN NOT NULL DEFAULT true,"createdById" TEXT REFERENCES "AdminUser"("id"),"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP NOT NULL);
CREATE TABLE "VisitorEvent" ("id" TEXT PRIMARY KEY,"visitorId" TEXT NOT NULL REFERENCES "Visitor"("id") ON DELETE CASCADE,"type" "VisitorEventType" NOT NULL,"url" TEXT,"title" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "Visitor_visitorId_idx" ON "Visitor"("visitorId"); CREATE INDEX "Visitor_lastSeenAt_idx" ON "Visitor"("lastSeenAt"); CREATE INDEX "Visitor_online_idx" ON "Visitor"("online"); CREATE INDEX "Conversation_visitorId_idx" ON "Conversation"("visitorId"); CREATE INDEX "Conversation_status_idx" ON "Conversation"("status"); CREATE INDEX "Conversation_updatedAt_idx" ON "Conversation"("updatedAt"); CREATE INDEX "Message_conversationId_idx" ON "Message"("conversationId"); CREATE INDEX "Message_createdAt_idx" ON "Message"("createdAt"); CREATE INDEX "QuickReply_siteId_idx" ON "QuickReply"("siteId"); CREATE INDEX "VisitorEvent_visitorId_idx" ON "VisitorEvent"("visitorId"); CREATE INDEX "VisitorEvent_type_idx" ON "VisitorEvent"("type"); CREATE INDEX "VisitorEvent_createdAt_idx" ON "VisitorEvent"("createdAt");
